on: [push]

name: okteto-preview-env

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
    - uses: okteto/login@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: "Deploy the preview environment"
      uses: okteto/deploy-preview@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: dev-previews-dsf
